### ISSUE TITLE
Hint spam after entering a vehicle

### ISSUE THREAD

**Issue by ir0n1e** [Dorbedo/Kerberos#2]
I think one time is enough   
![20171218164507_1](https://user-images.githubusercontent.com/8662872/34158522-13c5bf6e-e4c6-11e7-878c-6448a56db477.jpg)

**Comment by Dorbedo** [comment]
Ohhh, wieso existiert das Repo in der Öffentlichkeit.....
Ich schau es mir mal an.

https://github.com/Brig13Team/Operation_Kerberos
